### ISSUE TITLE
.

### ISSUE THREAD

**Issue by stefanodvx** [federicorosso1993/Kamyroll-CSharp#1]
Ciao, apro un issue perchè non ho idea di come fare in altro modo. Vorrei mettermi in contatto con te, hai qualche piattaforma dove poter parlare in chat, come Discord o Telegram?

**Comment by federicorosso1993** [comment]
Ho telegram ma vorrei evitare di diffonderlo qui. Non so come usare discord particolarmente bene ma se sai usarlo il mio username è lief#6416

Se hai reddit mi trovi come LiefLayer
